//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright Ezpie at http://ezpie.ai.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevWorkspace) DeepCopyInto(out *DevWorkspace) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevWorkspace.
func (in *DevWorkspace) DeepCopy() *DevWorkspace {
	if in == nil {
		return nil
	}
	out := new(DevWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevWorkspace) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevWorkspaceList) DeepCopyInto(out *DevWorkspaceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DevWorkspace, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevWorkspaceList.
func (in *DevWorkspaceList) DeepCopy() *DevWorkspaceList {
	if in == nil {
		return nil
	}
	out := new(DevWorkspaceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DevWorkspaceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevWorkspaceSpec) DeepCopyInto(out *DevWorkspaceSpec) {
	*out = *in
	out.Task = in.Task
	in.Data.DeepCopyInto(&out.Data)
	in.Workspace.DeepCopyInto(&out.Workspace)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevWorkspaceSpec.
func (in *DevWorkspaceSpec) DeepCopy() *DevWorkspaceSpec {
	if in == nil {
		return nil
	}
	out := new(DevWorkspaceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DevWorkspaceStatus) DeepCopyInto(out *DevWorkspaceStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DevWorkspaceStatus.
func (in *DevWorkspaceStatus) DeepCopy() *DevWorkspaceStatus {
	if in == nil {
		return nil
	}
	out := new(DevWorkspaceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EzData) DeepCopyInto(out *EzData) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]EzDataEntry, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EzData.
func (in *EzData) DeepCopy() *EzData {
	if in == nil {
		return nil
	}
	out := new(EzData)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EzDataEntry) DeepCopyInto(out *EzDataEntry) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EzDataEntry.
func (in *EzDataEntry) DeepCopy() *EzDataEntry {
	if in == nil {
		return nil
	}
	out := new(EzDataEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EzTask) DeepCopyInto(out *EzTask) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EzTask.
func (in *EzTask) DeepCopy() *EzTask {
	if in == nil {
		return nil
	}
	out := new(EzTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EzWorkspace) DeepCopyInto(out *EzWorkspace) {
	*out = *in
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]EzWorkspaceEnv, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EzWorkspace.
func (in *EzWorkspace) DeepCopy() *EzWorkspace {
	if in == nil {
		return nil
	}
	out := new(EzWorkspace)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EzWorkspaceEnv) DeepCopyInto(out *EzWorkspaceEnv) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EzWorkspaceEnv.
func (in *EzWorkspaceEnv) DeepCopy() *EzWorkspaceEnv {
	if in == nil {
		return nil
	}
	out := new(EzWorkspaceEnv)
	in.DeepCopyInto(out)
	return out
}
