name: Docker Image CI/CD

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Details
        run: |
          echo "⏰Trigger at `date +%Y%m%d%H%M%S`"
          echo "💡Build image with ${{ github.ref_name }}"

      - name: Build Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ez-supervisor:latest -t ${{ secrets.DOCKER_USERNAME }}/ez-supervisor:${{ github.ref_name }} .

      - name: Login to Registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ez-supervisor:${{ github.ref_name }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ez-supervisor:latest
