apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # 名字必需与下面的 spec 字段匹配，并且格式为 '<名称的复数形式>.<组名>'
  name: devworkspaces.stable.ezpie.ai
spec:
  # 组名称，用于 REST API: /apis/<组>/<版本>
  group: stable.ezpie.ai
  # 可以是 Namespaced 或 Cluster
  scope: Namespaced
  names:
    # 名称的复数形式，用于 URL：/apis/<组>/<版本>/<名称的复数形式>
    plural: devworkspaces
    # 名称的单数形式，作为命令行使用时和显示时的别名
    singular: devworkspace
    # kind 通常是单数形式的驼峰命名（CamelCased）形式。你的资源清单会使用这一形式。
    kind: DevWorkspace
    # shortNames 允许你在命令行使用较短的字符串来匹配资源
    shortNames:
      - dws
    # categories 是定制资源所归属的分类资源列表
    categories:
      - all
  # 列举此 CustomResourceDefinition 所支持的版本
  versions:
    - name: v1
      # 每个版本都可以通过 served 标志来独立启用或禁止
      served: true
      # 其中一个且只有一个版本必需被标记为存储版本
      storage: true
      schema:
        # schema used for validation
        openAPIV3Schema:
          type: object
          properties:
            # spec 定义
            spec:
              type: object
              properties:
                # spec 定义开始
                deploymentName:
                  type: string
                replicas:
                  type: integer
                  minimum: 1
                  maximum: 10
            # status 定义
            status:
              type: object
              properties:
                # status 定义开始
                availableReplicas:
                  type: integer
      # subresources for the custom resource
      subresources:
        # enables the status subresource
        status: { }
      additionalPrinterColumns:
        - name: Deploy
          type: string
          description: The name of deployment
          jsonPath: .spec.deploymentName
        - name: R
          type: integer
          description: The replicas
          jsonPath: .spec.replicas
          # 优先级默认为 0，大于 0 的列只会在宽视图（使用 -o wide 标志）中显示
          priority: 1